version: "2"

linters:
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: false
      exclude-functions:
        - (*database/sql.Tx).Rollback
        - (*database/sql.Rows).Close
        - (io.Closer).Close
        - (*os.File).Close
      verbose: true
