version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - embeddedstructfieldcheck
    # - err113 #TODO
    - forbidigo

  settings:
    depguard:
      rules:
        main:
          list-mode: original
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "log$"
              desc: use app struct logger instead
            - pkg: "log/slog$"
              desc: use app struct logger instead

    embeddedstructfieldcheck:
      empty-line: true
      forbid-mutex: true

    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: false
      exclude-functions:
        - (*database/sql.Tx).Rollback
        - (*database/sql.Rows).Close
        - (io.Closer).Close
        - (*os.File).Close
      verbose: true

    forbidigo:
      exclude-godoc-examples: false
      analyze-types: true
