name: Run Tests

on:
  workflow_dispatch:
  push:

env:
  GITHUB_REF: ${{ github.ref }}

permissions:
  contents: read

jobs:
  built-test-and-lint:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.GITHUB_REF }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Test it
        run: go test ./...
